# Generated by Django 4.2.2 on 2023-07-31 19:56

from django.db import migrations, models
import utilities.generator


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("present", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Freelancer",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=utilities.generator.id_generator,
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bio", models.TextField(blank=True, default="", max_length=1500)),
                (
                    "profession",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("skills", models.CharField(blank=True, default="", max_length=1000)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("region", models.CharField(blank=True, default="", max_length=50)),
                ("address", models.CharField(blank=True, default="", max_length=120)),
                ("country", models.CharField(default="", max_length=100)),
                (
                    "zip_code",
                    models.CharField(blank=True, default="00000", max_length=20),
                ),
                ("pricing", models.CharField(blank=True, default="100", max_length=20)),
                ("jobs_completed", models.IntegerField(default=0)),
                ("badge", models.CharField(default="basic", max_length=200)),
                ("bits", models.IntegerField(blank=True, default=60)),
                (
                    "education",
                    models.ManyToManyField(
                        blank=True,
                        related_name="freelancer",
                        to="freelancers.education",
                    ),
                ),
            ],
        ),
    ]
