# Generated by Django 5.0.2 on 2024-08-04 17:27

import utilities.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('image', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.CharField(default=utilities.generator.id_generator, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=1500)),
                ('bio', models.TextField(blank=True, default='', max_length=1500)),
                ('skills', models.CharField(blank=True, default='', max_length=1000)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('phone_code', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('district', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('zip_code', models.CharField(blank=True, default='00000', max_length=20)),
                ('pricing', models.CharField(blank=True, default='100', max_length=20)),
                ('jobs_completed', models.IntegerField(default=0)),
                ('badge', models.CharField(default='basic', max_length=200)),
                ('bits', models.IntegerField(blank=True, default=60)),
                ('education', models.ManyToManyField(blank=True, related_name='freelancer', to='freelancers.education')),
            ],
        ),
    ]
