# Generated by Django 4.2.2 on 2023-07-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reviews", "0001_initial"),
        ("freelancers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="freelancer",
            name="reviews",
            field=models.ManyToManyField(
                blank=True, related_name="freelancer_reviews", to="reviews.review"
            ),
        ),
    ]
