# Generated by Django 5.0.2 on 2024-08-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelancers', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='freelancer_reviews', to='reviews.review'),
        ),
    ]
