# Generated by Django 5.0.2 on 2024-09-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('organization', models.TextField()),
                ('url', models.URLField()),
                ('date_issued', models.DateTimeField()),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='freelancer',
            name='certificates',
            field=models.ManyToManyField(blank=True, related_name='freelancer', to='freelancers.certificate'),
        ),
    ]
