# Generated by Django 4.2.2 on 2023-08-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freelancers", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freelancer",
            name="profession",
        ),
        migrations.AddField(
            model_name="freelancer",
            name="title",
            field=models.CharField(blank=True, default="", max_length=1500),
        ),
    ]
