# Generated by Django 5.0.2 on 2024-05-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0004_remove_freelancer_profession_freelancer_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='region',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='address',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='phone_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
