# Generated by Django 5.0.2 on 2024-09-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0004_certificate_freelancer_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_issued',
            field=models.DateField(),
        ),
    ]
