# Generated by Django 5.0.2 on 2024-09-15 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0005_certificate_file_url_alter_certificate_date_issued'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='course',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='present',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.AddField(
            model_name='education',
            name='achievements',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
