# Generated by Django 5.0.2 on 2025-04-11 19:55

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                (
                    "public_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("avatar", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "gender",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_client", models.BooleanField(default=False)),
                ("is_talent", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("phone_code", models.CharField(blank=True, default="", max_length=10)),
                (
                    "country",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "state",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "district",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "city",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, default="00000", max_length=20, null=True
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="OTT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255, null=True)),
                ("code", models.CharField(max_length=8)),
                ("is_sent", models.BooleanField(default=False)),
                ("is_valid", models.BooleanField(default=False)),
                ("verified", models.BooleanField(default=False)),
                ("expire_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OTTProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.ott",),
        ),
    ]
