# Generated by Django 5.0.2 on 2025-02-08 18:29

import functools
import utilities.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="public_id",
            field=models.CharField(
                db_index=True,
                default=functools.partial(
                    utilities.generator.default_pid_generator, *("Usr",), **{}
                ),
                max_length=50,
            ),
        ),
    ]
