# Generated by Django 5.0.2 on 2025-04-13 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBillingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        help_text="The first line of the billing address.",
                        max_length=255,
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="The second line of the billing address (optional).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="The city of the billing address.", max_length=100
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="The state or region of the billing address.",
                        max_length=100,
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        help_text="The postal code of the billing address.",
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="The country of the billing address.", max_length=100
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="The phone number associated with the billing information.",
                        max_length=15,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserNotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payments",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications about payments and transactions.",
                    ),
                ),
                (
                    "messages",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications for new messages.",
                    ),
                ),
                (
                    "new_proposal",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications when you get new proposals.",
                    ),
                ),
                (
                    "job_updates",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications about job status changes.",
                    ),
                ),
                (
                    "email_newsletter",
                    models.BooleanField(
                        default=True,
                        help_text="Receive marketing emails and newsletters.",
                    ),
                ),
                (
                    "notification_delivery_method",
                    models.CharField(
                        choices=[
                            ("BOTH", "Both"),
                            ("PUSH_NOTIFICATION", "Push Notification"),
                            ("EMAIL_NOTOFICATION", "Email Notofication"),
                        ],
                        default="BOTH",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        help_text="The card number for the payment method.",
                        max_length=16,
                    ),
                ),
                (
                    "card_holder_name",
                    models.CharField(
                        help_text="The name of the cardholder.", max_length=255
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(help_text="The expiration date of the card."),
                ),
                (
                    "cvv",
                    models.CharField(
                        help_text="The CVV code of the card.", max_length=4
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is the default payment method.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPrivacySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_visiblity",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("PRIVATE", "Private"),
                            ("CONTACTS", "Contacts"),
                        ],
                        default="PUBLIC",
                        help_text="Control who can see your profile information.",
                        max_length=50,
                    ),
                ),
                (
                    "online_status",
                    models.BooleanField(
                        default=True, help_text="Show when you are online to others."
                    ),
                ),
                (
                    "last_seen",
                    models.BooleanField(
                        default=True,
                        help_text="Show when you were last active on the platform.",
                    ),
                ),
                (
                    "seo_indexing",
                    models.BooleanField(
                        default=False,
                        help_text="Allow search engines to index your profile.",
                    ),
                ),
                (
                    "show_earnings",
                    models.BooleanField(
                        default=False,
                        help_text="Display your earnings on your public profile.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSecuritySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tfa_enabled",
                    models.BooleanField(
                        default=False, help_text="Two-Factor Authentication"
                    ),
                ),
                (
                    "session_timeout",
                    models.CharField(
                        help_text="Automatically log out after a period of inactivity.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "login_otifications",
                    models.BooleanField(
                        default=True,
                        help_text="Receive notifications when a new login is detected on your account.",
                        null=True,
                    ),
                ),
                (
                    "multiple_sessions",
                    models.BooleanField(
                        default=False,
                        help_text="Allow your account to be logged in on multiple devices simultaneously.",
                        null=True,
                    ),
                ),
                (
                    "failed_login_attemp",
                    models.IntegerField(
                        choices=[
                            (0, "Unlimited"),
                            (3, "Three Attemps"),
                            (5, "Five Attemps"),
                            (10, "Ten Attemps"),
                        ],
                        default=0,
                        help_text="Limit the number of failed login attempts before locking the account.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "password_reset_period",
                    models.CharField(
                        choices=[
                            ("NEVER", "Never"),
                            ("EVERY_YEAR", "Every Year"),
                            ("EVERY_MONTH", "Every Month"),
                            ("EVERY_3_MONTHS", "Every 3 Months"),
                            ("EVERY_6_MONTHS", "Every 6 Months"),
                            ("EVERY_9_MONTHS", "Every 9 Months"),
                        ],
                        default="NEVER",
                        help_text="Require users to reset their password after a certain period.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "ip_restriction",
                    models.BooleanField(
                        default=False,
                        help_text="Restrict access to your account from specific IP addresses.",
                        null=True,
                    ),
                ),
                (
                    "ip_whitelist",
                    models.TextField(
                        blank=True, help_text="IP addresses to allow.", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("EN", "English"),
                            ("FR", "French"),
                            ("ES", "Spanish"),
                            ("PT", "Portuguese"),
                        ],
                        default="EN",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "preferred_currency",
                    models.CharField(
                        choices=[
                            ("GMD", "Gambian Dalasis"),
                            ("CFA", "CFA Franc"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                        ],
                        default="GMD",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "billing_info",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_preference",
                        to="users.userbillinginfo",
                    ),
                ),
                (
                    "notification_settings",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_preference",
                        to="users.usernotificationsetting",
                    ),
                ),
                (
                    "payment_methods",
                    models.ManyToManyField(
                        blank=True,
                        related_name="user_preference",
                        to="users.userpaymentmethod",
                    ),
                ),
                (
                    "privacy_settings",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_preference",
                        to="users.userprivacysettings",
                    ),
                ),
                (
                    "security_settings",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_preference",
                        to="users.usersecuritysettings",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
