# Generated by Django 4.2.2 on 2023-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="websocket_id",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
