# Generated by Django 5.0.2 on 2025-04-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
