# Generated by Django 5.0.2 on 2025-04-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userbillinginfo_usernotificationsetting_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersecuritysettings",
            name="failed_login_attemp",
            field=models.IntegerField(
                choices=[
                    (0, "Unlimited"),
                    (3, "Three Attemps"),
                    (5, "Five Attemps"),
                    (10, "Ten Attemps"),
                ],
                default=0,
                help_text="Limit the number of failed login attempts before locking the account.",
                null=True,
            ),
        ),
    ]
