# Generated by Django 5.0.2 on 2025-03-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_public_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="public_id",
        ),
    ]
