# Generated by Django 5.0.2 on 2025-03-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_public_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="reviews",
        ),
    ]
