# Generated by Django 5.0.2 on 2024-05-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='identifier',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
