# Generated by Django 5.0.2 on 2025-03-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="ott",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
