# Generated by Django 5.0.2 on 2024-05-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otp_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
