# Generated by Django 5.0.2 on 2024-05-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_paymentmethod_user_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
