# Generated by Django 5.1.1 on 2024-10-19 14:16

import django.core.serializers.json
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bits_count', models.IntegerField(default=0)),
                ('hired_count', models.IntegerField(default=0)),
                ('invite_count', models.IntegerField(default=0)),
                ('proposal_count', models.IntegerField(default=0)),
                ('interview_count', models.IntegerField(default=0)),
                ('unanswered_invites', models.IntegerField(default=0)),
                ('client_last_visit', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('pricing', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('benefits', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('required_skills', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('country', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance'), ('contract', 'Contract'), ('internship', 'Internship')], db_index=True, default='freelance', max_length=20)),
                ('published', models.BooleanField(blank=True, default=False)),
                ('status', models.CharField(choices=[('CLOSED', 'Closed'), ('PUBLISHED', 'Published'), ('SUSPENDED', 'Suspended'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='CLOSED', max_length=200)),
                ('href', models.URLField(blank=True, null=True)),
                ('is_valid', models.BooleanField(blank=True, default=True)),
                ('views_count', models.IntegerField(default=0)),
                ('proposal_count', models.IntegerField(default=0)),
                ('invitation_count', models.IntegerField(default=0)),
                ('client_last_visit', models.DateTimeField(blank=True, null=True)),
                ('experience_level', models.CharField(blank=True, null=True)),
                ('estimated_duration', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('bits_amount', models.IntegerField(default=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_valid', '-created_at', 'published'],
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fixed_price', models.BooleanField(blank=True, default=True, help_text='fixed price? If not, the price will be negotiable.')),
                ('negotiable_price', models.BooleanField(blank=True, default=False, help_text='open to negotiate the price?')),
                ('will_pay_more', models.BooleanField(blank=True, default=False, help_text='willing to pay more than the budget?')),
                ('addition_node', models.CharField(help_text='any additional information regarding the payment.', max_length=100)),
                ('payment_type', models.CharField(default='PROJECT', help_text='payment type. project or hourly.', max_length=100)),
            ],
        ),
    ]
