# Generated by Django 5.0.2 on 2025-04-02 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        ("core", "0001_initial"),
        ("jobs", "0001_initial"),
        ("talents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="hired",
            field=models.ManyToManyField(blank=True, to="talents.talent"),
        ),
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.category",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="activities",
            name="job",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity",
                to="jobs.job",
            ),
        ),
        migrations.CreateModel(
            name="JobAgentProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("jobs.job",),
        ),
    ]
