# Generated by Django 5.1.1 on 2024-10-19 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0002_initial"),
        ("core", "0001_initial"),
        ("jobs", "0001_initial"),
        ("talents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="hired",
            field=models.ManyToManyField(blank=True, to="talents.talent"),
        ),
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.category",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="clients.client",
            ),
        ),
    ]
