# Generated by Django 5.1.1 on 2024-10-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="experience_level",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
