# Generated by Django 5.0.2 on 2025-02-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='additional_payment_terms',
            field=models.CharField(blank=True, default=''),
        ),
    ]
