# Generated by Django 5.0.2 on 2024-08-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='bits_count',
            field=models.IntegerField(default=0),
        ),
    ]
