# Generated by Django 5.0.2 on 2025-02-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="estimated_duration",
            field=models.CharField(blank=True, null=True),
        ),
    ]
