# Generated by Django 4.2.2 on 2023-08-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
