# Generated by Django 5.0.2 on 2025-04-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="applicant_ids",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
