# Generated by Django 5.0.2 on 2024-08-17 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_activities_bits_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='invitations',
        ),
        migrations.RemoveField(
            model_name='activities',
            name='proposals',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='client_last_visit',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='interview_count',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='job',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='proposals',
        ),
        migrations.AddField(
            model_name='invitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='job_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
