# Generated by Django 5.0.2 on 2025-04-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_applicant_ids"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pricing",
        ),
        migrations.AlterField(
            model_name="activities",
            name="bits_count",
            field=models.IntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name="activities",
            name="hired_count",
            field=models.IntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name="activities",
            name="interview_count",
            field=models.IntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name="activities",
            name="invite_count",
            field=models.IntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name="activities",
            name="proposal_count",
            field=models.IntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name="activities",
            name="unanswered_invites",
            field=models.IntegerField(db_default=0),
        ),
    ]
