# Generated by Django 5.0.2 on 2025-02-18 03:07

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_estimated_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobAgentProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("jobs.job",),
        ),
        migrations.AddField(
            model_name="job",
            name="third_party_metadata",
            field=models.JSONField(
                blank=True,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
