# Generated by Django 5.0.2 on 2025-04-05 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_delete_jobagentproxy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activities",
            name="job",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity",
                to="jobs.job",
            ),
        ),
    ]
