# Generated by Django 4.2.2 on 2023-08-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="job_type",
        ),
    ]
