# Generated by Django 5.0.2 on 2024-05-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_valid',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='active_state',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
