# Generated by Django 5.0.2 on 2025-03-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_jobagentproxy_job_third_party_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("CLOSED", "Closed"),
                    ("PUBLISHED", "Published"),
                    ("SUSPENDED", "Suspended"),
                    ("COMPLETED", "Completed"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DELETED", "Deleted"),
                ],
                default="CLOSED",
                max_length=200,
            ),
        ),
    ]
