# Generated by Django 5.0.2 on 2025-04-05 17:00

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_activities_job"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="job",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
