# Generated by Django 5.1.1 on 2024-10-20 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
