# Generated by Django 5.0.2 on 2025-03-23 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_job_is_deleted_alter_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="job",
            name="public_id",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
