# Generated by Django 5.0.2 on 2024-08-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_slug_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('FULL-TIME', 'Full Time'), ('PART-TIME', 'Part Time'), ('FREELANCE', 'Freelance'), ('CONTRACT', 'Contract')], db_index=True, default='FREELANCE', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
