# Generated by Django 5.0.2 on 2024-05-19 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0004_remove_freelancer_profession_freelancer_title'),
        ('jobs', '0005_job_is_valid_alter_job_active_state'),
        ('proposals', '0006_alter_proposal_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='client_last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='activities',
            name='interview_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activities',
            name='invites_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activities',
            name='proposal_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activities',
            name='unanswered_invites',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='pricing',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='activities',
            name='proposals',
            field=models.ManyToManyField(related_name='proposals', to='proposals.proposal'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_count', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(blank=True, default=False)),
                ('client_last_visit', models.DateTimeField(blank=True, null=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancers.freelancer')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='jobs.job')),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proposals.proposal')),
                ('proposals', models.ManyToManyField(related_name='job_proposals', to='proposals.proposal')),
            ],
        ),
    ]
