# Generated by Django 5.0.2 on 2025-04-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_job_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="job",
            managers=[],
        ),
    ]
