# Generated by Django 5.0.2 on 2025-04-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_job_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="activities",
            name="applicants_id",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
