# Generated by Django 5.0.2 on 2025-03-27 13:44

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_alter_job_created_at_alter_job_public_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="invitation_count",
        ),
        migrations.RemoveField(
            model_name="job",
            name="proposal_count",
        ),
        migrations.RemoveField(
            model_name="job",
            name="views_count",
        ),
        migrations.AddField(
            model_name="job",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
