# Generated by Django 5.1.1 on 2024-10-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_activities_job"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="href",
            new_name="third_party_address",
        ),
        migrations.AddField(
            model_name="job",
            name="is_third_party",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
