# Generated by Django 5.0.2 on 2024-09-21 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_type_alter_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applications_deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='href',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='pricing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_pricing', to='jobs.pricing'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('CLOSED', 'Closed'), ('SUSPENDED', 'Suspended'), ('PUBLISHED', 'Published'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='CLOSED', max_length=200),
        ),
    ]
