# Generated by Django 5.0.2 on 2024-11-04 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_initial'),
        ('jobs', '0007_rename_href_job_third_party_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='activities',
            name='job',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='clients.client'),
            preserve_default=False,
        ),
    ]
