# Generated by Django 5.0.2 on 2024-05-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0004_remove_freelancer_profession_freelancer_title'),
        ('jobs', '0008_activities_hired_activities_hired_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='hired',
            field=models.ManyToManyField(blank=True, to='freelancers.freelancer'),
        ),
        migrations.RemoveField(
            model_name='activities',
            name='hired_count',
        ),
        migrations.AddField(
            model_name='activities',
            name='hired_count',
            field=models.IntegerField(default=0),
        ),
    ]
