# Generated by Django 5.0.2 on 2025-03-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_alter_job_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("CLOSED", "Closed"),
                    ("PENDING", "Pending"),
                    ("PUBLISHED", "Published"),
                    ("SUSPENDED", "Suspended"),
                    ("COMPLETED", "Completed"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DELETED", "Deleted"),
                    ("CONTRACTED", "Contracted"),
                ],
                default="PENDING",
                max_length=200,
            ),
        ),
    ]
