# Generated by Django 5.0.2 on 2024-05-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_activities_hired_remove_activities_hired_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='invites_counts',
            new_name='invite_counts',
        ),
    ]
