# Generated by Django 5.0.2 on 2024-05-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_rename_invites_counts_activities_invite_counts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='invite_counts',
            new_name='invite_count',
        ),
    ]
