# Generated by Django 5.0.2 on 2024-05-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_rename_invite_counts_activities_invite_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
