# Generated by Django 5.0.2 on 2024-05-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='bits_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
