# Generated by Django 5.0.2 on 2024-05-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_job_bits_count_alter_job_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='active_state',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('CLOSED', 'Closed'), ('PUBLISHED', 'Published'), ('SUSPENDED', 'Suspended'), ('IN_PROGRESS', 'In Progress')], default='CLOSED', max_length=200),
        ),
    ]
