# Generated by Django 5.0.2 on 2024-07-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='category',
            new_name='category_obj',
        ),
    ]
