# Generated by Django 5.0.2 on 2024-08-11 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_pk', models.CharField(db_index=True, max_length=255)),
                ('milestone_name', models.CharField(blank=True, max_length=255, null=True)),
                ('milestone_description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_final', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=255)),
                ('acknowledgement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone', to='projects.acknowledgement')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('acknowledgement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ack_project', to='projects.acknowledgement')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('milestones', models.ManyToManyField(related_name='milestone_project', to='projects.milestone')),
            ],
        ),
    ]
