# Generated by Django 5.0.2 on 2025-03-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="milestones",
        ),
        migrations.AddField(
            model_name="milestone",
            name="client_comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("DECLIEND", "Decliend"),
                    ("ACCEPTED", "Accepted"),
                    ("ACTIVE", "Active"),
                ],
                default="ACTIVE",
                max_length=255,
            ),
        ),
    ]
