# Generated by Django 5.0.2 on 2025-03-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0002_remove_project_milestones_milestone_client_comment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="public_id",
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
    ]
