# Generated by Django 5.0.2 on 2024-08-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_duration_alter_project_acknowledgement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLOSED', 'Closed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('TERMINATED', 'Terminated')], default='PENDING', max_length=20),
        ),
    ]
