# Generated by Django 5.0.2 on 2024-08-13 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ACCEPTED', 'Accepted'), ('ACTIVE', 'Active')], default='ACTIVE', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='acknowledgement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='projects.acknowledgement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='milestones',
            field=models.ManyToManyField(blank=True, related_name='milestone_project', to='projects.milestone'),
        ),
    ]
