# Generated by Django 5.0.2 on 2025-03-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="milestones",
            field=models.ManyToManyField(
                blank=True, related_name="milestone_project", to="projects.milestone"
            ),
        ),
    ]
