# Generated by Django 5.0.2 on 2025-03-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_milestones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("CLOSED", "Closed"),
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("TERMINATED", "Terminated"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
