# Generated by Django 5.0.2 on 2024-08-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_milestone_status_alter_project_acknowledgement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='milestone',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
