# Generated by Django 5.0.2 on 2024-08-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_options_milestone_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
