# Generated by Django 5.0.2 on 2025-03-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="rejection_comment",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("CLOSED", "Closed"),
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("TERMINATED", "Terminated"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
