# Generated by Django 5.0.2 on 2024-08-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_milestone_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['due_date']},
        ),
        migrations.AddField(
            model_name='project',
            name='acceptance_comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cancellation_comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='system_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='termination_comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('CLOSED', 'Closed'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('TERMINATED', 'Terminated')], default='PENDING', max_length=20),
        ),
    ]
