# Generated by Django 4.2.2 on 2023-08-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="unique_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
