# Generated by Django 5.0.2 on 2024-08-04 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('freelancers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancers.freelancer'),
        ),
    ]
