# Generated by Django 5.0.2 on 2024-06-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_additional_terms_contract_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='client_acknowledgement',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=200),
        ),
        migrations.AddField(
            model_name='contract',
            name='freelancer_acknowledgement',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=200),
        ),
    ]
