# Generated by Django 5.0.2 on 2024-11-04 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0003_initial'),
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talents.talent'),
        ),
    ]
