# Generated by Django 5.0.2 on 2024-06-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_client_acknowledgement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='client_project_acknowledgement',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=200),
        ),
    ]
