# Generated by Django 5.0.2 on 2025-03-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="client_comment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("TERMINATED", "Terminated"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("TERMINATED", "Terminated"),
                ],
                default="PENDING",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="talent_acknowledgement",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("TERMINATED", "Terminated"),
                ],
                default="PENDING",
                max_length=200,
            ),
        ),
    ]
