# Generated by Django 5.0.2 on 2024-07-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_client_project_acknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='completed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
