# Generated by Django 5.0.2 on 2025-03-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_contract_client_comment_alter_contract_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="public_id",
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
    ]
