# Generated by Django 5.0.2 on 2024-07-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contract_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
