# Generated by Django 5.0.2 on 2025-02-08 15:34

import django.core.serializers.json
import functools
import utilities.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=utilities.generator.primary_key_generator, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, default=functools.partial(utilities.generator.default_pid_generator, *('Client',), **{}), max_length=50)),
                ('about', models.TextField(blank=True, max_length=1500, null=True)),
                ('reviews_count', models.IntegerField(blank=True, default=0)),
                ('country', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, max_length=500, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=1000)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=utilities.generator.primary_key_generator, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, default=functools.partial(utilities.generator.default_pid_generator, *('',), **{}), max_length=50)),
                ('name', models.CharField(default='', max_length=1000, unique=True)),
                ('description', models.TextField(default='', max_length=1500)),
                ('website', models.CharField(blank=True, default='', max_length=1000)),
                ('industry', models.CharField(blank=True, default='', max_length=1000)),
                ('date_established', models.DateField(blank=True, null=True)),
                ('logo_url', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
