# Generated by Django 5.0.2 on 2024-08-04 17:27

import utilities.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(default=utilities.generator.id_generator, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('bio', models.TextField(default='', max_length=1500)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('phone_code', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('district', models.CharField(blank=True, default='', max_length=50)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('zip_code', models.CharField(blank=True, default='00000', max_length=20)),
                ('website', models.CharField(blank=True, default='', max_length=1000)),
                ('industry', models.CharField(blank=True, default='', max_length=1000)),
                ('jobs_active', models.IntegerField(default=0)),
                ('jobs_created', models.IntegerField(default=0)),
                ('jobs_completed', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
