# Generated by Django 5.0.2 on 2025-04-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="reviews",
            field=models.ManyToManyField(
                blank=True, related_name="client", to="reviews.review"
            ),
        ),
    ]
