# Generated by Django 5.0.2 on 2024-08-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='client', to='reviews.review'),
        ),
    ]
