# Generated by Django 5.0.2 on 2024-05-19 02:01

import django.db.models.deletion
import utilities.generator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('rating', models.IntegerField(default=0)),
                ('content', models.TextField(default='', max_length=500)),
                ('id', models.CharField(default=utilities.generator.id_generator, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='client', to='clients.review'),
        ),
    ]
