# Generated by Django 5.0.2 on 2024-05-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_rating_review_client_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
