# Generated by Django 5.0.2 on 2025-02-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="logo_url",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
    ]
