# Generated by Django 5.0.2 on 2025-04-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="_company",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="rating",
            field=models.FloatField(blank=True, default=0, max_length=5),
        ),
    ]
