# Generated by Django 5.0.2 on 2025-02-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_client_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_agent",
            field=models.BooleanField(default=False),
        ),
    ]
