# Generated by Django 5.0.2 on 2024-05-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='jobs_active',
            field=models.IntegerField(default=0),
        ),
    ]
