# Generated by Django 5.0.2 on 2024-05-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_jobs_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='about',
            new_name='bio',
        ),
    ]
