# Generated by Django 5.0.2 on 2025-03-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_client_is_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="public_id",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
