# Generated by Django 5.0.2 on 2025-03-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_alter_client_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="public_id",
            field=models.UUIDField(blank=True, max_length=100),
        ),
    ]
