# Generated by Django 5.0.2 on 2025-03-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_company_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="public_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
