# Generated by Django 5.0.2 on 2024-05-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_rename_region_client_district_remove_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
