# Generated by Django 5.0.2 on 2024-06-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_country_code_client_phone_code'),
        ('reviews', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='client', to='reviews.review'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
