# Generated by Django 5.0.2 on 2025-04-02 19:48

import functools

import django.db.models.deletion
from django.db import migrations, models

import utilities.generator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        default=functools.partial(
                            utilities.generator.default_pid_generator, *("A",), **{}
                        ),
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("file_url", models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        db_index=True,
                        default=functools.partial(
                            utilities.generator.default_pid_generator, *("PR",), **{}
                        ),
                        max_length=50,
                    ),
                ),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
                ("cover_letter", models.TextField(max_length=1500)),
                ("budget", models.FloatField(blank=True, default=0)),
                (
                    "service_fee",
                    models.FloatField(
                        blank=True, default=0.0, help_text="In percentage"
                    ),
                ),
                ("bits_amount", models.IntegerField(blank=True, default=12)),
                ("is_reviewed", models.BooleanField(default=False)),
                (
                    "client_comment",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REVIEW", "Review"),
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("CONTRACTED", "Contracted"),
                            ("DECLINED", "Declined"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="PENDING",
                        max_length=200,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True, related_name="proposal", to="proposals.attachment"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="jobs.job",
                    ),
                ),
            ],
        ),
    ]
