# Generated by Django 5.1.1 on 2024-10-19 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposals', '0001_initial'),
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='talents.talent'),
        ),
    ]
