# Generated by Django 4.2.2 on 2023-08-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="hourly_rate",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="discount",
            field=models.FloatField(blank=True, default=0.06),
        ),
    ]
