# Generated by Django 5.0.2 on 2025-02-09 13:44

import functools
import utilities.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="public_id",
            field=models.CharField(
                db_index=True,
                default=functools.partial(
                    utilities.generator.default_pid_generator, *("A",), **{}
                ),
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="public_id",
            field=models.CharField(
                db_index=True,
                default=functools.partial(
                    utilities.generator.default_pid_generator, *("PR",), **{}
                ),
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("REVIEW", "Review"),
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("TERMINATED", "Terminated"),
                ],
                default="PENDING",
                max_length=200,
            ),
        ),
    ]
