# Generated by Django 4.2.2 on 2023-08-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0002_proposal_hourly_rate_alter_proposal_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
