# Generated by Django 5.0.2 on 2025-02-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "proposals",
            "0003_alter_attachment_public_id_alter_proposal_public_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="client_comment",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
