# Generated by Django 5.0.2 on 2025-02-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0004_proposal_client_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, related_name="proposal", to="proposals.attachment"
            ),
        ),
    ]
