# Generated by Django 5.0.2 on 2025-03-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposals", "0005_alter_proposal_attachments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("REVIEW", "Review"),
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("CONTRACTED", "Contracted"),
                    ("DECLINED", "Declined"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("TERMINATED", "Terminated"),
                ],
                default="PENDING",
                max_length=200,
            ),
        ),
    ]
