# Generated by Django 5.0.2 on 2024-05-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_rename_discount_proposal_service_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='service_fee',
            field=models.FloatField(blank=True, default=0.06, help_text='In percentage'),
        ),
    ]
