# Generated by Django 5.0.2 on 2024-05-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_alter_proposal_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
