# Generated by Django 5.0.2 on 2024-05-30 23:19

import utilities.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_proposal_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='uid',
            field=models.CharField(default=utilities.generator.hex_generator, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
