# Generated by Django 5.0.2 on 2024-08-04 17:27

import utilities.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.CharField(default=utilities.generator.id_generator, editable=False, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
