# Generated by Django 5.0.2 on 2025-03-19 09:24

from django.db import migrations, models

import utilities.generator


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_managers"),
        ("staffs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="reviews",
            field=models.ManyToManyField(
                blank=True, related_name="staff_reviews", to="reviews.review"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="id",
            field=models.CharField(
                default=utilities.generator.primary_key_generator,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
