# Generated by Django 5.0.2 on 2025-03-30 18:48

from django.db import migrations, models

import utilities.generator


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0003_staff_reviews_alter_staff_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="id",
            field=models.UUIDField(
                default=utilities.generator.primary_key_generator,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
