# Generated by Django 5.0.2 on 2025-02-08 15:34

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField(default=5)),
                ("text", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
