# Generated by Django 5.0.2 on 2024-08-04 17:27

import django.db.models.manager
import utilities.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(default=utilities.generator.hex_generator, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=5)),
                ('text', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
