# Generated by Django 5.0.2 on 2025-03-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="review",
            managers=[],
        ),
    ]
