# Generated by Django 5.0.2 on 2025-03-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_valid",
            field=models.BooleanField(default=False),
        ),
    ]
