# Generated by Django 5.0.2 on 2024-07-08 01:14

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
