# Generated by Django 5.0.2 on 2025-03-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_review_is_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
    ]
