# Generated by Django 5.0.2 on 2024-08-04 17:27

import utilities.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(blank=True, default=utilities.generator.hex_generator, max_length=64, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.CharField(blank=True, default=utilities.generator.hex_generator, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_id', models.CharField(default='', max_length=100)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
    ]
