# Generated by Django 4.2.2 on 2023-08-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_thread_unique_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="messaging",
            options={"get_latest_by": "created_at"},
        ),
        migrations.AlterModelOptions(
            name="thread",
            options={"get_latest_by": "created_at"},
        ),
    ]
