# Generated by Django 5.0.2 on 2024-08-04 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_messenging_options_alter_thread_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messaging',
            new_name='Message',
        ),
    ]
