# Generated by Django 5.0.2 on 2025-02-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
