# Generated by Django 5.0.2 on 2025-04-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talent",
            name="badge",
            field=models.CharField(db_index=True, default="basic", max_length=200),
        ),
        migrations.AlterField(
            model_name="talent",
            name="pricing",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="talent",
            name="rating",
            field=models.FloatField(blank=True, db_index=True, default=3.5),
        ),
        migrations.AlterField(
            model_name="talent",
            name="title",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=1500
            ),
        ),
    ]
