# Generated by Django 5.0.2 on 2025-02-08 21:12

import utilities.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talent",
            name="id",
            field=models.CharField(
                default=utilities.generator.primary_key_generator,
                editable=False,
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
