# Generated by Django 5.0.2 on 2025-04-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="talent",
            name="applications_ids",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
