# Generated by Django 5.0.2 on 2025-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talents", "0003_alter_talent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="public_id",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
