# Generated by Django 5.0.2 on 2025-03-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talents", "0004_alter_portfolio_public_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="talent",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="public_id",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="education",
            name="public_id",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="talent",
            name="public_id",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
