# Generated by Django 5.0.2 on 2025-03-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talents", "0005_talent_deleted_at_alter_certificate_public_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="talent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
