# Generated by Django 5.0.2 on 2025-03-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talents", "0006_talent_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="talent",
            name="rating",
            field=models.IntegerField(blank=True, default=3.5),
        ),
    ]
