# Generated by Django 5.0.2 on 2025-03-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talents", "0007_talent_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="talent",
            name="dob",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
