# Generated by Django 5.0.2 on 2025-03-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("talents", "0008_talent_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talent",
            name="rating",
            field=models.FloatField(blank=True, default=3.5),
        ),
    ]
