# Generated by Django 4.2.2 on 2023-07-31 19:56

from django.db import migrations, models
import utilities.generator


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.CharField(
                        blank=True,
                        default=utilities.generator.hex_generator,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hint_text", models.CharField(default="", max_length=300)),
                ("content_text", models.CharField(default="", max_length=1000)),
                ("is_seen", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("type", models.CharField(default="PROPOSAL", max_length=60)),
            ],
        ),
    ]
