# Generated by Django 5.0.2 on 2025-02-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_emailed",
            field=models.BooleanField(default=True),
        ),
    ]
