name: Dokoola Backend Deployment CI/CD

on:
  workflow_run:
    workflows: ["Dokoola Backend Dockerizing CI/CD"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -X GET ${{secrets.DEPLOYMENT_URL}}
