name: Deploy The Backend-Service

on:
  workflow_run:
    workflows: ["Dokoola Backend Scaffold-Setup CI/CD"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST https://api.github.com/repos/dokoola/backend-scaffold-setup/dispatches
