name: Dockerize CI/CD

on:
  workflow_run:
    workflows: ["Scaffolding CI/CD"]
    types:
      - completed
    branches: ["main"]
  # push:
  #   branches: ["main"]

jobs:
  docker-image:
    name: Dockerize
    runs-on: ubuntu-latest

    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
      - run: echo ${{secrets.DOCKER_HUB_ACCESS_TOKEN}} | docker login -u ${{secrets.DOCKER_HUB_ACCOUNT}} --password-stdin

      - name: Build the Docker image
        run: sh build.sh

      - name: Push the Docker image
        run: sh push.sh ${{ github.sha }}
