name: Dokoola Backend Docker-Image CI/CD

on:
  workflow_run:
    workflows: ["Dokoola Backend Scaffold-Setup CI/CD"]
    types:
      - completed

jobs:
  docker-image:
    name: Dockerize
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo ${{secrets.DOCKER_HUB_ACCESS_TOKEN}} | docker login -u ${{secrets.DOCKER_HUB_ACCOUNT}} --password-stdin

      - name: Build the Docker image
        run: sh build.sh

      - name: Push the Docker image
        run: sh push.sh
