name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo ${{secrets.DOCKER_HUB_ACCESS_TOKEN}} | docker login -u ${{secrets.DOCKER_HUB_ACCOUNT}} --password-stdin

      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: sh build.sh

      - uses: actions/checkout@v4
      - name: Push the Docker image
        run: sh push.sh
