name: Scaffolding CI/CD

on:
  workflow_run:
    workflows: ["Testing CI/CD"]
    types:
      - completed

jobs:
  scaffold:
    runs-on: ubuntu-latest
    name: Scaffold

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    container: python:3.12-slim

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.prod.txt

      - name: Setup Environments
        run: cp ./.env.prod ./.env

      - name: Run Scafollding
        run: python manage.py scaffold
