name: Scaffolding CI/CD

on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: ["main"]

jobs:
  scaffold:
    runs-on: ubuntu-latest
    name: Scaffold

    container: python:3.12-slim

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Setup Environments
        run: cp ./.env.prod ./.env

      - name: Run Scafollding
        run: python manage.py scaffold
