name: Scaffolding CI/CD

on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test App

    container: python:3.12-slim

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.dev.txt

      - name: Run Test
        run: sh pytest.sh

      - name: Upload Test
        uses: trunk-io/analytics-uploader@main
        with:
          junit-paths: ./*.xml
          org-slug: dokoola
          token: ${{ secrets.TRUNK_API_TOKEN }}

  scaffold:
    runs-on: ubuntu-latest
    name: Scaffold
    needs: test
    if: success()

    container: python:3.12-slim

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.prod.txt

      - name: Setup Environments
        run: cp ./.env.prod ./.env

      - name: Run Scafollding
        run: python manage.py scaffold
