name: Testing CI/CD

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test App

    container: python:3.12-slim

    steps:
      - name: Install Test dependencies
        run: pip install --no-cache-dir -r requirements.test.txt

      - name: Setup Test Environments
        run: cp ./.env.test ./.env

      - name: Make and Run Migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run Test
        run: sh pytest.sh
        continue-on-error: true

      - name: Upload Test Reports
        uses: trunk-io/analytics-uploader@main
        with:
          junit-paths: ./*.xml
          org-slug: dokoola
          token: ${{ secrets.TRUNK_API_KEY }}

        continue-on-error: true
